default: &default
   adapter: postgresql
   encoding: unicode
  


development:
  adapter: postgresql
  database: ticketee_development
  username: yakose
  password: Jtkvplez1604


test:
   adapter: postgresql
   encoding: unicode
   database: ticketee_test
   username: yakose
   password: Jtkvplez1604
 
production:
   adapter: postgresql
   encoding: unicode
   database: ticketee_production
   username: yakose
   password: Jtkvplez1604
